/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * merk.java
 *
 * Created on Jun 8, 2013, 9:49:32 PM
 */
package subform;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksi.koneksi;
public class Hotel extends javax.swing.JInternalFrame {

    Statement stt;
    ResultSet rss;
    DefaultTableModel model;
    String type;
    public Hotel() {
        initComponents();
        tabelKerusakan();
        loadtabel();
        btnbatal.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblkerusakan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnbaru = new javax.swing.JButton();
        btnubahn = new javax.swing.JButton();
        txtjenis = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        txtjenis1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        tblkerusakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nomor Kamar", "Harga", "Id"
            }
        ));
        tblkerusakan.setName("tblhotel"); // NOI18N
        tblkerusakan.setRowHeight(20);
        tblkerusakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkerusakanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkerusakan);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Data Kamar Hotel");

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Trash-can-icon.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel2.setText("Nomor Kamar");

        btnbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/File-New-icon.png"))); // NOI18N
        btnbaru.setText("Baru");
        btnbaru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });

        btnubahn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-document-edit-icon.png"))); // NOI18N
        btnubahn.setText("Ubah");
        btnubahn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnubahn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahnActionPerformed(evt);
            }
        });

        txtjenis.setEnabled(false);

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save-icon.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsimpan.setEnabled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/no-icon.png"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbatal.setPreferredSize(new java.awt.Dimension(83, 25));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        txtjenis1.setEnabled(false);

        jLabel4.setText("Harga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnubahn)
                .addGap(83, 83, 83)
                .addComponent(btnsimpan)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjenis1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjenis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbaru)
                    .addComponent(btnubahn)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tblkerusakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkerusakanMouseClicked
    int row=tblkerusakan.getSelectedRow();
    txtjenis.setText((String)tblkerusakan.getValueAt(row, 1));
    txtjenis1.setText((String)tblkerusakan.getValueAt(row, 2));
    txtjenis.setEnabled(true);
    txtjenis1.setEnabled(true);
    
    btnsimpan.setEnabled(false);
}//GEN-LAST:event_tblkerusakanMouseClicked

private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
    Connection con = new koneksi().getCn();
    int row=tblkerusakan.getSelectedRow();
    try
        {   if(row==-1){
                JOptionPane.showMessageDialog(this, "Pilih salah satu tabel untuk dihapus","Pesan",JOptionPane.WARNING_MESSAGE);
            }else{
                String idp = tblkerusakan.getModel().getValueAt(row,0).toString();
                String sql="DELETE FROM kamar_hotel WHERE id = '"+idp+"'";
                int kom=JOptionPane.showConfirmDialog(null, "Apa Anda yakin ingin menghapus salah satu data?","Konfirmasi penghapusan",JOptionPane.YES_NO_OPTION);
                if(kom==JOptionPane.YES_OPTION){
                    stt = con.createStatement();
                    stt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus","Pesan",JOptionPane.INFORMATION_MESSAGE);
                    tabelKerusakan();
                    loadtabel();
                    clear();
                    txtjenis.setEnabled(false);
            }
            }
        } 
        catch (Exception e)
        {
            e.printStackTrace();
        }
}//GEN-LAST:event_btnhapusActionPerformed

private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
btnsimpan.setEnabled(true);
btnhapus.setVisible(false);
btnubahn.setEnabled(false);
btnbatal.setVisible(true);
txtjenis.setEnabled(true);
txtjenis1.setEnabled(true);
clear();
}//GEN-LAST:event_btnbaruActionPerformed

private void btnubahnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahnActionPerformed
    Connection con = new koneksi().getCn();
    int row=tblkerusakan.getSelectedRow();
    try
        {   
            if(row==-1){
                JOptionPane.showMessageDialog(this, "Pilih salah satu tabel","Pesan",JOptionPane.WARNING_MESSAGE);
            }else{
                String idp = tblkerusakan.getModel().getValueAt(row,0).toString();
                String nomor_kamar = txtjenis.getText();
                String harga  = txtjenis1.getText();
                
                String sql="UPDATE kamar_hotel SET  nomor_kamar ='"+nomor_kamar+"', harga='"+harga+"'  WHERE id='"+idp+"'";
                PreparedStatement p = con.prepareStatement(sql);
               // p.setString(1, txtjenis.getText());   
                p.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah","Pesan",JOptionPane.INFORMATION_MESSAGE);
                tabelKerusakan();
                loadtabel();
                clear();
                txtjenis.setEnabled(false);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Gagal Ubah");
            e.printStackTrace();
        }
}//GEN-LAST:event_btnubahnActionPerformed

private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
Connection con = new koneksi().getCn();try
        {
            if(txtjenis.getText().equals("") || txtjenis1.getText().equals("") ){
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
            }
            else {
                
                String nomor_kamar = txtjenis.getText();
                String harga  = txtjenis1.getText();
                
                String sql="insert into kamar_hotel (nomor_kamar,harga) values('"+nomor_kamar+"','"+harga+"')";
                PreparedStatement p = con.prepareStatement(sql);
                p.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil masuk","Pesan",JOptionPane.INFORMATION_MESSAGE);
                tabelKerusakan();
                loadtabel();
                clear();
                btnbatal.setVisible(false);
                btnhapus.setVisible(true);
                btnubahn.setEnabled(true);
                btnsimpan.setEnabled(false);
            }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Gagal Simpan");
            e.printStackTrace();
        }
}//GEN-LAST:event_btnsimpanActionPerformed

private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
clear();
btnubahn.setEnabled(true);
btnhapus.setVisible(true);
btnbatal.setVisible(false);
btnsimpan.setEnabled(false);
txtjenis.setEnabled(false);
}//GEN-LAST:event_btnbatalActionPerformed

public void tabelKerusakan(){
    model = new DefaultTableModel();
    tblkerusakan.setModel(model);
    model.addColumn("Id");
    model.addColumn("Nomor Kamar");
    model.addColumn("Harga");
    aturKolom();
}
public void aturKolom(){ 
    TableColumn column;
    tblkerusakan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
    column = tblkerusakan.getColumnModel().getColumn(2); 
    column.setPreferredWidth(340);
    column = tblkerusakan.getColumnModel().getColumn(1); 
    column.setPreferredWidth(110); 
    column = tblkerusakan.getColumnModel().getColumn(0); 
    column.setPreferredWidth(50); 
}
public void loadtabel(){
    Connection con = new koneksi().getCn();
    String sql = "SELECT * FROM kamar_hotel";
    try{
        stt = con.createStatement();
        rss = stt.executeQuery(sql);
        while(rss.next()){
            Object[] o = new Object[3];
                o[0] = rss.getString("id");
                o[1] = rss.getString("nomor_kamar");
                o[2] = rss.getString("harga");
                //type = rss.getString("type");
                model.addRow(o);
        }
        rss.close();
    }catch(Exception e){
            e.printStackTrace();
    }
}
public void clear(){
    txtjenis.setText("");
     txtjenis1.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubahn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkerusakan;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtjenis1;
    // End of variables declaration//GEN-END:variables
}
