/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * solusi.java
 *
 * Created on Jun 8, 2013, 10:55:20 PM
 */
package subform;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksi.koneksi;
public class Pemesanan extends javax.swing.JInternalFrame {

    Statement stt;
    ResultSet rss;
    DefaultTableModel model;
    public Pemesanan() {
        initComponents();
        tabelKerusakan();
        loadtabel();
        loaddata2();
        loadcombo();
        loadcombolama_pemesanan();
        loadcombostatus();
        btnsimpan.setVisible(true);
        
        btnbatal.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbaru = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkerusakan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        cmb_type = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmb_type1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmb_type2 = new javax.swing.JComboBox();
        cmb_type3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);

        btnbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/File-New-icon.png"))); // NOI18N
        btnbaru.setText("Baru");
        btnbaru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save-icon.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsimpan.setEnabled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/no-icon.png"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbatal.setPreferredSize(new java.awt.Dimension(83, 25));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        tblkerusakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Customer", "Kamar", "Lama Pemesanan", "Status Pemesanan"
            }
        ));
        tblkerusakan.setName("tblkerusakan"); // NOI18N
        tblkerusakan.setRowHeight(20);
        tblkerusakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkerusakanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkerusakan);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Pemesanan");

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Trash-can-icon.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        cmb_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        cmb_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb_typeMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmb_typeMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_typeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmb_typeMouseExited(evt);
            }
        });
        cmb_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_typeItemStateChanged(evt);
            }
        });
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Customer");

        cmb_type1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_type1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        cmb_type1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_type1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmb_type1MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmb_type1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb_type1MouseReleased(evt);
            }
        });
        cmb_type1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_type1ItemStateChanged(evt);
            }
        });
        cmb_type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_type1ActionPerformed(evt);
            }
        });

        jLabel5.setText("No Kamar");

        cmb_type2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_type2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        cmb_type2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_type2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmb_type2MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmb_type2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb_type2MouseReleased(evt);
            }
        });
        cmb_type2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_type2ItemStateChanged(evt);
            }
        });
        cmb_type2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_type2ActionPerformed(evt);
            }
        });

        cmb_type3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_type3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        cmb_type3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_type3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmb_type3MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmb_type3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb_type3MouseReleased(evt);
            }
        });
        cmb_type3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_type3ItemStateChanged(evt);
            }
        });
        cmb_type3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_type3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Lama Pemesanan");

        jLabel7.setText("Status Pemesanan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_type2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_type3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(btnsimpan)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_type2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_type3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbaru)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
btnsimpan.setEnabled(true);
btnhapus.setVisible(false);

btnbatal.setVisible(true);

clear();
}//GEN-LAST:event_btnbaruActionPerformed

private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
Connection con = new koneksi().getCn();
try
        {
            String nama_customer = cmb_type.getSelectedItem().toString();
            String no_kamar      = cmb_type1.getSelectedItem().toString();
            String Lama_Pemesanan = cmb_type2.getSelectedItem().toString();
            String Status_Pemesanan = cmb_type3.getSelectedItem().toString();
           
            
                String sql= "insert into `order` (`id_customer`,`id_hotel`,`lama_pemesanan`,`status_pemesanan`) values('"+nama_customer+"','"+no_kamar+"','"+Lama_Pemesanan+"','"+Status_Pemesanan+"')";
                PreparedStatement p = con.prepareStatement(sql);
                p.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil masuk","Pesan",JOptionPane.INFORMATION_MESSAGE);
                tabelKerusakan();
                loadtabel();
                clear();
                btnbatal.setVisible(false);
                btnhapus.setVisible(true);
              
                btnsimpan.setEnabled(false);
            
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Gagal Simpan");
            e.printStackTrace();
        }
}//GEN-LAST:event_btnsimpanActionPerformed

private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
clear();

btnhapus.setVisible(true);
btnbatal.setVisible(false);
btnsimpan.setEnabled(true);
//txtjenis.setEnabled(false);
}//GEN-LAST:event_btnbatalActionPerformed

private void tblkerusakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkerusakanMouseClicked
    int row=tblkerusakan.getSelectedRow();
  //  txtjenis.setText((String)tblkerusakan.getValueAt(row, 1));
//    /txtjenis.setEnabled(true);
    btnsimpan.setEnabled(true);
}//GEN-LAST:event_tblkerusakanMouseClicked

private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
    Connection con = new koneksi().getCn();
    int row=tblkerusakan.getSelectedRow();
    try
        {   if(row==-1){
                JOptionPane.showMessageDialog(this, "Pilih salah satu tabel untuk dihapus","Pesan",JOptionPane.WARNING_MESSAGE);
            }else{
                String idp = tblkerusakan.getModel().getValueAt(row,0).toString();
                String sql="DELETE FROM `order` WHERE id = '"+idp+"'";
                int kom=JOptionPane.showConfirmDialog(null, "Apa Anda yakin ingin menghapus salah satu data?","Konfirmasi penghapusan",JOptionPane.YES_NO_OPTION);
                if(kom==JOptionPane.YES_OPTION){
                    stt = con.createStatement();
                    stt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus","Pesan",JOptionPane.INFORMATION_MESSAGE);
                    tabelKerusakan();
                    loadtabel();
                    clear();
                    //txtjenis.setEnabled(false);
            }
            }
        } 
        catch (Exception e)
        {
            e.printStackTrace();
        }
}//GEN-LAST:event_btnhapusActionPerformed

    private void cmb_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_typeMouseClicked

    }//GEN-LAST:event_cmb_typeMouseClicked

    private void cmb_typeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_typeMousePressed

    }//GEN-LAST:event_cmb_typeMousePressed

    private void cmb_typeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_typeMouseExited

    }//GEN-LAST:event_cmb_typeMouseExited

    private void cmb_typeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_typeMouseReleased

    }//GEN-LAST:event_cmb_typeMouseReleased

    private void cmb_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_typeItemStateChanged

    }//GEN-LAST:event_cmb_typeItemStateChanged

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_typeActionPerformed

    private void cmb_type1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type1MouseClicked

    private void cmb_type1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type1MousePressed

    private void cmb_type1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type1MouseExited

    private void cmb_type1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type1MouseReleased

    private void cmb_type1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_type1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type1ItemStateChanged

    private void cmb_type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_type1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type1ActionPerformed

    private void cmb_type2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type2MouseClicked

    private void cmb_type2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type2MousePressed

    private void cmb_type2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type2MouseExited

    private void cmb_type2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type2MouseReleased

    private void cmb_type2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_type2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type2ItemStateChanged

    private void cmb_type2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_type2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type2ActionPerformed

    private void cmb_type3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type3MouseClicked

    private void cmb_type3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type3MousePressed

    private void cmb_type3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type3MouseExited

    private void cmb_type3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_type3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type3MouseReleased

    private void cmb_type3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_type3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type3ItemStateChanged

    private void cmb_type3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_type3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_type3ActionPerformed
public void tabelKerusakan(){
    model = new DefaultTableModel();
    tblkerusakan.setModel(model);
    model.addColumn("Id");
    model.addColumn("Nama Pemesan");
    model.addColumn("No Kamar");
    model.addColumn("Status PEmesanan");
    model.addColumn("Lama Pemesanan");
    aturKolom();
}
public void aturKolom(){ 
    TableColumn column;
    tblkerusakan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
    column = tblkerusakan.getColumnModel().getColumn(0); 
    column.setPreferredWidth(50);
    column = tblkerusakan.getColumnModel().getColumn(1); 
    column.setPreferredWidth(100);
    column = tblkerusakan.getColumnModel().getColumn(2); 
    column.setPreferredWidth(100);
    column = tblkerusakan.getColumnModel().getColumn(3); 
    column.setPreferredWidth(100);
    column = tblkerusakan.getColumnModel().getColumn(4); 
    column.setPreferredWidth(100);
}
public void loadtabel(){
    Connection con = new koneksi().getCn();
    String sql = "SELECT * FROM `order` ";
    try{
        stt = con.createStatement();
        rss = stt.executeQuery(sql);
        while(rss.next()){
            Object[] o = new Object[6];
                o[0] = rss.getString("id");
                o[1] = rss.getString("id_customer");
                o[2] = rss.getString("id_hotel");
                o[3] = rss.getString("lama_pemesanan");
                o[4] = rss.getString("status_pemesanan");
                model.addRow(o);
        }
        rss.close();
    }catch(Exception e){
            e.printStackTrace();
    }
}
public void loaddata2(){
    Connection con = new koneksi().getCn();
    String sql = "SELECT nama FROM customer";
    try{
        stt = con.createStatement();
        rss = stt.executeQuery(sql);
        while(rss.next()){
                cmb_type.addItem(rss.getString("nama"));
        }
        rss.close();
    }catch(Exception e){
            e.printStackTrace();
    }
}


public void loadcombo(){
    Connection con = new koneksi().getCn();
    String sql = "SELECT nomor_kamar FROM kamar_hotel";
    try{
        stt = con.createStatement();
        rss = stt.executeQuery(sql);
        while(rss.next()){
                cmb_type1.addItem(rss.getString("nomor_kamar"));
        }
        rss.close();
    }catch(Exception e){
            e.printStackTrace();
    }
}
public void loadcombolama_pemesanan(){

                cmb_type2.addItem("ShortTime");
                cmb_type2.addItem("LongTime");
}

public void loadcombostatus(){

                cmb_type3.addItem("CheckIn");
                cmb_type3.addItem("CheckOut");
}

public void clear(){
   // txtjenis.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox cmb_type;
    private javax.swing.JComboBox cmb_type1;
    private javax.swing.JComboBox cmb_type2;
    private javax.swing.JComboBox cmb_type3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkerusakan;
    // End of variables declaration//GEN-END:variables
}
